JambulaTV: Fix bug that caused kodi application to crash during initial startup            This was due to our earlier deletion of the required kodi addon:            service.xbmc.versioncheck in /usr/share/kodi/addons
* When --debug is called with kodi, the trace log for this looks like:

           ERROR: Unable to create application. Exiting
           /usr/bin/kodi: line 175:  4910 Segmentation fault (core dumped)
           "$LIBDIR/${bin_name}/${bin_name}.bin" $SAVED_ARGS